language: android
android:
  components:
    # Tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

script:
     - ./gradlew clean build
     - ./gradlew connectedCheck