language: android
android:
  components:
    # Tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    licenses:
    - android-sdk-license-.+

    # Emulators
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

  script:
    - ./gradlew clean build
    - ./gradlew build connectedCheck